apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 5775
              protocol: UDP
              name: udp-5775
            - containerPort: 6831
              protocol: UDP
              name: udp-6831
            - containerPort: 6832
              protocol: UDP
              name: udp-6832
            - containerPort: 5778
              name: http-5778
            - containerPort: 16686
              name: http-16686
            - containerPort: 14250
              name: grpc-14250
            - containerPort: 14268
              name: http-14268
            - containerPort: 14269
              name: http-14269
            - containerPort: 9411
              name: http-9411
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: MEMORY_MAX_TRACES
              value: "50000"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 10
            periodSeconds: 5
