apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  labels:
    app: jaeger
spec:
  ports:
    - port: 16686
      name: http-16686
      targetPort: 16686
      nodePort: 30686
  selector:
    app: jaeger
  type: NodePort
