apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 1024
        timeout: 1s
        send_batch_max_size: 1024

    exporters:
      jaeger:
        endpoint: "jaeger:14250"
        tls:
          insecure: true

      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "ticket_service"

      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, logging]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]
