apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticket-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - ticketservice.yaml
  - hpa.yaml
