apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - name: http
      protocol: TCP
      port: 4040
      targetPort: 4040
  type: ClusterIP
