receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 1s
    send_batch_max_size: 2048
  
  # Add service name and version to all traces
  resource:
    attributes:
      - key: deployment.environment
        value: "docker"
        action: upsert

  # Sample traces to reduce volume (adjust as needed)
  probabilistic_sampler:
    sampling_percentage: 100

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "ticketer"

  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource, probabilistic_sampler]
      exporters: [jaeger, logging]

    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, logging]

  extensions: []