apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  labels:
    app: rabbitmq
type: Opaque
data:
  # Base64 encoded credentials
  rabbitmq-username: Z3Vlc3Q=  # 'guest'
  rabbitmq-password: Z3Vlc3Q=  # 'guest'
