version: '3.8'

services:
  # ticketservice:
  #   image: ${DOCKER_REGISTRY-}ticketservice
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TicketServiceDb;Username=postgres;Password=postgres;
  #     - DatabaseProvider=PostgreSQL
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - ticket-network
  #   restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=TicketServiceDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network
    restart: unless-stopped

networks:
  ticket-network:
    driver: bridge

volumes:
  postgres-data:
