apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: default
  labels:
    app: nginx-ingress-controller
data:
  proxy-connect-timeout: "15"
  proxy-send-timeout: "600"
  proxy-read-timeout: "600"
  proxy-body-size: "32m"
  proxy-buffer-size: "64k"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "false"
  enable-real-ip: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: default