apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - name: http
      protocol: TCP
      port: 5266
      targetPort: 80
  type: ClusterIP
