apiVersion: v1
kind: Service
metadata:
  name: booking-db
  labels:
    app: booking-db
spec:
  selector:
    app: booking-db
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
