apiVersion: v1
kind: Service
metadata:
  name: bookingservice
  labels:
    app: bookingservice
spec:
  selector:
    app: bookingservice
  ports:
    - name: http
      protocol: TCP
      port: 5200
      targetPort: 80
  type: ClusterIP
