apiVersion: v1
kind: Service
metadata:
  name: ticketservice
  labels:
    app: ticketservice
spec:
  selector:
    app: ticketservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5300
  type: ClusterIP
