apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-db-pvc
  labels:
    app: ticket-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
