apiVersion: v1
kind: Service
metadata:
  name: ticket-db
  labels:
    app: ticket-db
spec:
  selector:
    app: ticket-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
