apiVersion: v1
kind: Service
metadata:
  name: notification-db
  labels:
    app: notification-db
spec:
  selector:
    app: notification-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
