apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.ui.service.port }}
      name: http-ui
      targetPort: 16686
      nodePort: {{ .Values.ui.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.ui.service.type }}
