apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
