apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
  namespace: ticketer
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-booking-pvc
  namespace: ticketer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ticket-pvc
  namespace: ticketer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage
  resources:
    requests:
      storage: 10Gi
