apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
        - name: events-service
          image: ticketer/events-service:latest
          ports:
            - containerPort: 4041
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://events-db:5432/events_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            # OpenTelemetry configuration
            - name: OTLP_TRACING_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "events-service"
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 4041
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 4041
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
