# Docker Compose file for Authentication Service
services:
  auth-service:
    build:
      context: .
      # Uncomment the line below to use the simplified Dockerfile if the layered one fails
      # dockerfile: Dockerfile.simple
    restart: always
    ports:
      - 4040:4040
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - ticketer-network

  auth-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ticketer-network

volumes:
  auth-db-data:

networks:
  ticketer-network:
    driver: bridge

